### ISSUE TITLE
(tert-butoxy)carbohydrazide mistranslation

### ISSUE THREAD

**Issue by paconius** [dan2097/opsin#143]
CC(C)(C)OC(=O)NN has IUPAC name (tert-butoxy)carbohydrazide according to both ChemDraw and ChemAxon.
OPSIN gives a different structure for this name.

**Comment by dan2097** [comment]
ChemAxon's naming of this compound as (tert-butoxy)carbohydrazide is incorrect. ChemAxon appears to be treating carbohydrazide as a suffix which is invalid as there's no group to apply the suffix to.

ChemDraw gives this compound the IUPAC name: tert-butyl hydrazinecarboxylate
I do observe that ChemDraw round trips ChemAxon's name, but note that ChemDraw avoids the ambiguity by not supporting the name carbohydrazide (https://en.wikipedia.org/wiki/Carbohydrazide)

I'm not too sure how to deal with this sort of issue, as while OPSIN does aim to support real-world nomenclature, this only occurs in the real-world due to a bug in ChemAxon's naming algorithm

**Comment by paconius** [comment]
Okay. Thanks for taking a look. I have a whole bunch of files full of "carbohydrazide" I need to go back and edit!😲
