### ISSUE TITLE
A space difference will create two different structure

### ISSUE THREAD

**Issue by leonqli** [dan2097/opsin#164]
Please take a look of this case that two names are different in "one" space after the bracket, i.e. bis(2-hydroxyethyl)oleylamine and bis(2-hydroxyethyl) oleylamine, but create totally different structures. 

* bis(2-hydroxyethyl)oleylamine
![image](https://user-images.githubusercontent.com/1482243/143019697-504af9b6-b416-48a2-a1e3-a6a13d24c8ee.png)

* bis(2-hydroxyethyl) oleylamine 
![image](https://user-images.githubusercontent.com/1482243/143019752-c7221a82-c5fb-445e-bb11-fa8b93d162c7.png)

**Comment by dan2097** [comment]
Thanks, OPSIN uses heuristics when two substituents are next to each other as to whether they should be joined end to end or attached the next group in the name. i.e. whether bis(2-hydroxyethyl)oleylamine means (bis(2-hydroxyethyl)oleyl)amine or bis(2-hydroxyethyl)(oleyl)amine. Ideally such cases probably should be reported as ambiguous although this would be quite a large change.

For bis(2-hydroxyethyl) oleylamine, the latter interpretation is always used as the susbtituents have been delimited (a hyphen instead of a space has the same effect).

One heuristic that OPSIN uses is that two alkyl chains shouldn't connect together, the traditional names for such chains were overlooked from this heuristic. I've implemented a fix, and I'm currently testing whether this change introduces any unexpected regressions before pushing it.

**Comment by dan2097** [comment]
Both names will now give the same interpretation (the structure shown for "bis(2-hydroxyethyl) oleylamine"). This change is live on opsin.ch.cam.ac.uk
