### ISSUE TITLE
Correct IUPAC name for one of the C11H8 carbenes

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#186]
Hi, I am wondering which name is correct here. Should we give low numbers for the double bonds or for the carbene? Kindly advice. Please see the image.
![c11h8-name](https://user-images.githubusercontent.com/70721856/163245725-5b1bed7f-9cf4-4845-b8a9-c713f9310f60.jpg)

**Comment by dan2097** [comment]
It's not really a question of the name being incorrect, as both do describe the same structure.

IUPAC does have a concept of a Preferred IUPAC names (PIN). However for this example, I think the PIN would in fact be:
1H-Benzo[7]annulen-1-ylidene
as can be seen by what ACD/Name assigns as the preferred IUPAC name for the parent compound (https://www.chemspider.com/Chemical-Structure.10614148.html)

Regarding your original question, I think the _ylidene_ is preferred to have a lower locant than the _ene_
I'm unfortunately not as familiar with the IUPAC preferred naming rules, so I wouldn't like to say definitively, OPSIN aims to accept all IUPAC-like names rather than just preferred ones.

**Comment by vthimmakondu** [comment]
Thank you for this. Please see page 23 of this attached document. I have highlighted one structure where the PIN was given based on the fact that _ene_ takes precedence over _ylidene_
[iupac-p3.pdf](https://github.com/dan2097/opsin/files/8493084/iupac-p3.pdf)

**Comment by dan2097** [comment]
> Thank you for this. Please see page 23 of this attached document. I have highlighted one structure where the PIN was given based on the fact that _ene_ takes precedence over _ylidene_ [iupac-p3.pdf](https://github.com/dan2097/opsin/files/8493084/iupac-p3.pdf)

I don't think I can see the highlighting in this document, which example was it specifically?

Using the first example on page 23 of that PDF (but-3-en-1-yl), which admitedly pertains to yl rather than ylidene. If ene took precedence, wouldn't this be but-1-en-4-yl

**Comment by vthimmakondu** [comment]
I agree.
