### ISSUE TITLE
Unable to generate name for one of the C5H isomers

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#210]
Hi,

Based on IUPAC name of one of the C5H2 isomers (2-cyclopropen-1-ylidenethenylidene), I am trying to generate the IUPAC name for C5H. However, OPSIN comes up with a error message called "Substitutive bond formation failure".
![Screenshot 2023-01-27 at 11-29-35 OPSIN Open Parser for Systematic IUPAC Nomenclature](https://user-images.githubusercontent.com/70721856/215180940-a533e551-4b3c-41a2-b9c3-7cb9fd8ece63.png)

If I remove one H-atom from the cyclopropene ring (so that to make it as an isomer of C5H) then the name should be 2-cyclopropenyl-1-ylidenethenylidene. But, I am unable to generate name for this isomer.
![IMG_9327](https://user-images.githubusercontent.com/70721856/215182091-ac4a99f0-c6a1-4e8a-96c2-6067eb4e3845.JPG)
Any help is appreciated.

**Comment by dan2097** [comment]
I think in this compound it is not possible to name it such that both radical centres are in the same parent group, necessitating naming one as a prefix. The IUPAC preferred way to do this is using the prefix ylo (cf. https://iupac.qmul.ac.uk/BlueBook/P7.html#7105)
Which I think would give the name:
(2-ylocycloprop-2-en-1-ylidene)ethenylidene

Having said that OPSIN doesn't yet support the _ylo_ prefix mainly because it's so rarely used in real world names.

OPSIN does support the lambda convention would would yield a name like:
(2λ<sup>3</sup>-cycloprop-2-en-1-ylidene)ethenylidene
(cf. https://iupac.qmul.ac.uk/BlueBook/P7.html#710205)

**Comment by vthimmakondu** [comment]
Thank you very much Dr. Lowe.
