### ISSUE TITLE
mvn package gives v3.0 SNAPSHOT

### ISSUE THREAD

**Issue by stuchalk** [dan2097/opsin#219]
Not sure if this is correct, but I just cloned and packaged opsin locally and it is version 3.0-SNAPSHOT.  Seeing that this version is not yet on GitHub, I was wondering if this was intended...

**Comment by dan2097** [comment]
It is intentional, it means that the latest SNAPSHOT of OPSIN has a constant version number, which makes it simpler to have another project always depend on the latest version. I'm not planning to break the API for the forseeable future, so there won't be a v3.0 for the forseeable future, the next release will likely be 2.8.0
