### ISSUE TITLE
InChI, StdInChI, and StdInChIKey Methods all returning null.

### ISSUE THREAD

**Issue by chejunkie** [dan2097/opsin#228]
I converted your library using the latest version of [IKVM](https://github.com/ikvmnet/ikvm/pkgs/nuget/IKVM).

ParseToSmiles works fine, but none of the inchi parse functions work. I also tried to pass in the result from parseChemicalName, and still nothing although the OpsinResult object shows SUCCESS status. 

It keeps throwing: 'java.lang.RuntimeException' in opsin.cli.dll

**Comment by chejunkie** [comment]
Quick update. I converted the previous version, same procedure as before, and it is working. So, I think that is my solution for now. As I cannot debug in to Java from C#, someone may want to double check the latest build 2.6 for issues with the parsers for the different flavors of inchi.

**Comment by dan2097** [comment]
OPSIN's InChI support comes from a wrapper around the InChI library which is a native C library, hence I can imagine that this may complicate the conversion. 
Between  v2.5.0 and v2.6.0 OPSIN switched from JNI-InChI, which as the name implies uses the Java Native Interface to https://github.com/dan2097/jna-inchi which uses Java Native Access. This was done primarily as JNI-InChI hasn't been updated since the release of InChI 1.03, while InChI 1.06 is current.

OPSIN is structured into three modules, opsin-core, opsin-inchi and opsin-cli. opsin-core does not include any InChI related code, and provides all the APIs except those specifically related to converting to InChI. Given that SMILES can be converted by other tools to InChI, for many use cases having the conversion to SMILES working is the only thing that really matters.

OPSIN's InChI module has the same API both in v2.5.0 and v2.7.0 so in principle a hybrid that uses the current opsin-core and older opsin-inchi can be built, but to avoid confusion between absolute and racemic stereo chemistry this condition really should  be included (this was only added post v2.5.0, when StereoGroup support was added):
https://github.com/dan2097/opsin/blob/298b54c98159d463a7251cd846601b382af134c3/opsin-inchi/src/main/java/uk/ac/cam/ch/wwmm/opsin/NameToInchi.java#L172C1-L175C11

**Comment by chejunkie** [comment]
Thank you for the detailed response, that helped. I tried to directly convert jna-inchi, but that did not work... Looking at the InChI Trust site, I can work directly with the source files from there if need. However, for my purposes, I will not need the newer InChI 1.06 version, so I am going to stick with the older Opsin 2.5 version for now as I already have that integrated in what I am doing. Also, now that you have you have enlightened me, I am noticing the older jni-chi library used in several chemoinformatic libraries like, e.g., RDKit... Anyways, thanks again for your response; the Opsin library is very useful, as I can use the SMILES output to link to many other libraries.
