### ISSUE TITLE
OPSIN generates incorrect structure for cycloprop-2-en-1-ylidenethenylidene

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#252]
Hi Dan,

I think that both 2-cyclopropen-1-ylidenethenylidene and cycloprop-2-en-1-ylidenethenylidene are one and the same isomer of C5H2 elemental composition but the latter name generates a structure that I feel is wrong. Here is the result:
![Screenshot 2024-04-16 at 11-16-23 OPSIN Open Parser for Systematic IUPAC Nomenclature](https://github.com/dan2097/opsin/assets/70721856/0d3d048e-0047-458d-ab37-9047452d0db4)

It's hard to comprehend what is going wrong here! Any help is appreciated.

Thanks,
Venky

**Comment by dan2097** [comment]
This is due to a parsing ambiguity that leads to there being two ways to breakdown the name into its components. 
Specifically is `ylidenethenylidene`  [yliden][eth][en][ylidene] or [ylidene][then][ylidene]  (thenyl is a trivial name for a radical derived from methylthiophene)

OPSIN tries each interpretation in turn, with a preference to the interpretation that requires fewest splits, meaning it tries the dubious intepretation first. `2-(cyclopropen-1-ylidene)thenylidene` is rejected for valency reasons, but `(cycloprop-2-en-1-ylidene)thenylidene` passes this check.

I'll investigate whether this can be added to the function that detects a few other common ambiguitities
e.g. tetradecyl, depending on context, can be 4 x 10 carbons [tetra][dec][yl] or 14 carbons [tetradec][yl]
